spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ztvzvajeihmxsetfgwsq
spring.datasource.password=MLDMUL012mldmul012

# how my data is handled at startup
spring.jpa.hibernate.ddl-auto=update  

# show sql statements in the console
spring.jpa.show-sql=true                  
server.port=9090